require_relative "tic_tac_toe/game"
require_relative "tic_tac_toe/board"
require_relative "tic_tac_toe/player"
require_relative "tic_tac_toe/computer"
require_relative "tic_tac_toe/dummy_ai"
require_relative "tic_tac_toe/dummy_ai/row_checker"
require_relative "tic_tac_toe/dummy_ai/column_checker"
require_relative "tic_tac_toe/dummy_ai/diagonal_checker"
