require_relative "tic_tac_toe/game"
require_relative "tic_tac_toe/printer"
require_relative "tic_tac_toe/board"
require_relative "tic_tac_toe/judge"
require_relative "tic_tac_toe/player"
require_relative "tic_tac_toe/computer"

require_relative "tic_tac_toe/ai/regexps"
require_relative "tic_tac_toe/ai"
require_relative "tic_tac_toe/ai/row_checker"
require_relative "tic_tac_toe/ai/column_checker"
require_relative "tic_tac_toe/ai/diagonal_checker"
